### ISSUE TITLE
Jekyll Page Built Failure: File to import not found or unreadable

### ISSUE THREAD

**Issue by HP-Nunes** [thoughtbot/bourbon#1063]
## Description

I am attempting to publish a jekyll theme ([end2end](https://github.com/nandomoreirame/end2end)) on my github.io page; however I keep running into the same error:

> "Your Sass file `css/main.sass` has an error on line 9: File to import not found or unreadable: bourbon. Load paths: _sass /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.3/_sass."

From what I understand there is an issue with the path directory between the `css/main.sass` and the location of the bourbon gem file; I notice from the error message that the path seems to be looping twice?

Perhaps the issue is because I only pushed to git the source folder? But If I need an index.html file in the root directory to publish with GitHub pages (if that's always the case), I thought the theme folder was for my own purposes when publishing in my local environment. I'm otherwise able to locally render the site with `bundle exec jekyll serve` (based on the jekyll set-up instructions from [GitHub Help](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-2-install-jekyll-using-bundler)). 

Tree directory
```
.
├── _config.yml
├── Gemfile
├── Gemfile.lock
├── install.sh
├── LICENSE
├── Rakefile
├── README.md
├── screenshot.png
├── _site
│   ├── 404.html
│   ├── about
│   │   └── index.html
│   ├── assets
│   │   ├── css
│   │   │   └── style.css
│   │   └── javascript
│   │       └── anchor-js
│   │           ├── anchor.js
│   │           ├── anchor.min.js
│   │           ├── banner.js
│   │           └── docs
│   │               ├── anchor.js
│   │               ├── favicon.ico
│   │               ├── fonts
│   │               │   ├── anchorjs-extras.eot
│   │               │   ├── anchorjs-extras.svg
│   │               │   ├── anchorjs-extras.ttf
│   │               │   ├── anchorjs-extras.woff
│   │               │   └── fonts.css
│   │               ├── grunticon
│   │               │   ├── grunticon.loader.js
│   │               │   ├── icons.data.png.css
│   │               │   ├── icons.data.svg.css
│   │               │   ├── icons.fallback.css
│   │               │   └── png
│   │               │       └── grunticon-link.png
│   │               ├── img
│   │               │   ├── anchoring-links.png
│   │               │   ├── anchorjs_logo.png
│   │               │   ├── anchorlinks2.png
│   │               │   ├── gh_link.svg
│   │               │   ├── gh-link.svg
│   │               │   ├── hyperlink.svg
│   │               │   ├── link.svg
│   │               │   ├── mini-logo.png
│   │               │   └── primer-md.png
│   │               ├── scripts.js
│   │               └── styles.css
│   ├── blog
│   │   ├── 2015
│   │   │   ├── a-wonderful-serenity-has-taken-possession-of-my-entire-soul
│   │   │   │   └── index.html
│   │   │   ├── far-far-away-behind-the-word-mountains-far-from-the-countries-vokalia-and-consonantia
│   │   │   │   └── index.html
│   │   │   ├── lorem
│   │   │   │   └── index.html
│   │   │   ├── lorem-ipsum-dolor-sit
│   │   │   │   └── index.html
│   │   │   ├── lorem-ipsum-dolor-sit-amet-consectetuer-adipiscing-elit
│   │   │   │   └── index.html
│   │   │   ├── the-quick-brown-fox-jumps-over-a-lazy-dog
│   │   │   │   └── index.html
│   │   │   └── welcome-to-jekyll
│   │   │       └── index.html
│   │   ├── index.html
│   │   └── page
│   │       ├── 2
│   │       │   └── index.html
│   │       └── 3
│   │           └── index.html
│   ├── css
│   │   └── main.css
│   ├── feed.xml
│   ├── fonts
│   │   ├── end2end.svg
│   │   ├── end2end.ttf
│   │   └── end2end.woff
│   ├── icons
│   │   └── index.html
│   ├── images
│   │   ├── avatar.jpg
│   │   └── placeholder.png
│   └── index.html
├── source
│   ├── 404.html
│   ├── about.md
│   ├── blog
│   │   └── index.html
│   ├── css
│   │   └── main.sass
│   ├── _data
│   │   └── _icons.yml
│   ├── feed.xml
│   ├── fonts
│   │   ├── end2end.svg
│   │   ├── end2end.ttf
│   │   └── end2end.woff
│   ├── icons.html
│   ├── images
│   │   ├── avatar.jpg
│   │   └── placeholder.png
│   ├── _includes
│   │   ├── article.html
│   │   ├── comments.html
│   │   ├── footer.html
│   │   ├── github-corner.html
│   │   ├── google_analytics.html
│   │   ├── header.html
│   │   ├── head.html
│   │   ├── pagination.html
│   │   └── social.html
│   ├── index.html
│   ├── _layouts
│   │   ├── default.html
│   │   ├── page.html
│   │   ├── pages.html
│   │   └── post.html
│   ├── _posts
│   │   ├── 2015-11-12-a-wonderful-serenity-has-taken-possession-of-my-entire-soul.md
│   │   ├── 2015-11-12-far-far-away-behind-the-word-mountains-far-from-the-countries-vokalia-and-consonantia.md
│   │   ├── 2015-11-12-lorem-ipsum-dolor-sit-amet-consectetuer-adipiscing-elit.md
│   │   ├── 2015-11-12-lorem.markdown
│   │   ├── 2015-11-12-the-quick-brown-fox-jumps-over-a-lazy-dog.md
│   │   ├── 2015-11-26-lorem-ipsum-dolor-sit.markdown
│   │   └── 2015-11-26-welcome-to-jekyll.markdown
│   └── _sass
│       ├── base
│       │   ├── _all.sass
│       │   ├── _blockquotes.sass
│       │   ├── _buttons.sass
│       │   ├── _forms.sass
│       │   ├── _helpers.sass
│       │   ├── _lists.sass
│       │   ├── _tables.sass
│       │   └── _typography.sass
│       ├── end2end
│       │   ├── _all.sass
│       │   ├── _articles.sass
│       │   ├── _base.sass
│       │   ├── _card.sass
│       │   ├── _footer.sass
│       │   ├── _github-corner.sass
│       │   ├── _header.sass
│       │   ├── _hero.sass
│       │   ├── _icons.sass
│       │   ├── _navbar.sass
│       │   ├── _pagination.sass
│       │   ├── _social.sass
│       │   └── _syntax.sass
│       ├── main.sass
│       ├── _mixins.sass
│       ├── _normalize.scss
│       ├── _placeholders.sass
│       └── _variables.sass
└── travisGemfile
```

css/main.sass

```
$output-bourbon-deprecation-warnings: false

@import "bourbon"

@import "variables"
@import "placeholders"
@import "mixins"

@import "normalize"
@import "base/all"
@import "end2end/all"
```
_config.yml
```
# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Hadrien's Wall.0
description: "HP-Nunes's portfolio and blog; using the end2end jekyll template"
keywords: ""
url: https://HP-Nunes.github.io
baseurl: ""

# Author settings
author:
  name: HP-Nunes
  job: Programmatic Geographer
  bio: 
  thumb: /images/avatar.jpg
  email: 
  url: https://HP-Nunes.github.io
  github: https://github.com/HP-Nunes
  twitter: https://twitter.com/geocuriosity
  linkedin: https://www.linkedin.com/in/hadnunpi/

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
```

Gemfile
```
source "https://rubygems.org"

gem "jekyll", "~>3.6.0"
gem "rake", "~>10.5"
gem "sass", "~>3.4"
gem "json", "~> 2"

# run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# Plugins
group :jekyll_plugins do
  gem "bourbon", "~>4.3"
  gem "jekyll-feed", "~>0.6"
  gem "jekyll-paginate-v2"
  gem "pygments.rb"
  gem "jekyll-compose"
  gem "kramdown"
end
```

## Development Environment
- jekyll version: 3.6.2
- Bourbon version: 4.3.4
- Platform: Ubuntu 18.04
- Github repo: https://github.com/HP-Nunes/HP-Nunes.github.io
