### ISSUE TITLE
suggestion: font-face

### ISSUE THREAD

**Issue by FDiskas** [thoughtbot/bourbon#1080]
There is a problem when custom font is not loaded - website does not displays text - just blank.
To solve issue please add to the mixin
`font-display: swap;` 

More info: https://css-tricks.com/almanac/properties/f/font-display/

**Comment by tysongach** [comment]
Can you please provide more detail? What environment are you working within? What fonts are you trying to load and from where? Are you seeing loading errors?

Also, you can specify `font-display` already (via Sass’s `@content`):

```scss
@include font-face(
  "source-sans-pro",
  "fonts/source-sans-pro-regular",
  ("woff2")
) {
  font-display: swap;
}
```

**Comment by FDiskas** [comment]
```scss
@import '~node_modules/bourbon/core/bourbon';
@include font-face('GothamLight', './fonts/Gotham-ExtraLight', ('otf')) {
    font-style: normal;
    font-weight: 400;
}
```
![image](https://user-images.githubusercontent.com/468006/61083599-ddec0d00-a434-11e9-9c41-b9dcd360c814.png)
