### ISSUE TITLE
CSS custom properties skipped in position()

### ISSUE THREAD

**Issue by meduzen** [thoughtbot/bourbon#1086]
## Description

A CSS custom property used as edge value in the `position()` mixin is skipped.

## Steps to Reproduce

```scss
.my-selector {
  --my-var: 10rem;

  @include position(absolute, 5rem var(--my-var) null null);
}
```

Output:
```scss
.my-selector {
  --my-var: 10rem;

  position: absolute;
  top: 5rem;
}
```

Expected:
```scss
.my-selector {
  --my-var: 10rem;

  position: absolute;
  top: 5rem;
  right: var(--my-var); // this one is missing
}
```

Under the hood, it happens because the `position` mixin [ensures the edges are proper CSS lengths using `is-length`](https://github.com/thoughtbot/bourbon/blob/6ef70918ccdc0b5b049180a3071e4f978b9d9a99/core/bourbon/library/_position.scss#L58).

[`is-length` allows `calc()`](https://github.com/thoughtbot/bourbon/blob/04ac693bda30294ecb359aa97c43a3ee1b97c2a7/core/bourbon/validators/_is-length.scss#L12), but unfortunately it doesn’t allow [`var()`](https://developer.mozilla.org/en-US/docs/Web/CSS/var) nor [`env()`](https://developer.mozilla.org/en-US/docs/Web/CSS/env).

Would you accept a PR for this?

I’m not a fan of enforcing values (at least for `position`): if the value isn’t valid, the browser will naturally skip it. I think the responsibility for validation should be on the CSS author side, not on Bourbon side.

## Development Environment

Bourbon 5.0, MacOS, node-sass.
