### ISSUE TITLE
Create a shortcut for targeting vedor prefixed ::placeholder selectors

### ISSUE THREAD

**Issue by plapier** [thoughtbot/bourbon#150]
I wrote this with the intent to introduce it to Bourbon. It generates the proper selector I hoped for, but the ruleset gets completely dropped by all browsers. Apparently you cannot chain the vendor-prefixed selectors, because if the browser fails on one of the prefixes, it drops the entire ruleset.

Ref this chrome bug: http://code.google.com/p/chromium/issues/detail?id=102691

Demo: http://jsfiddle.net/suprMax/jLTz9/
### Generate a variable containing the list of placeholder selectors

``` scss

$placeholders: '-webkit-input-placeholder',
               '-moz-placeholder',
               '-ms-input-placeholder';
$compiled-placeholder:  ();
$compiled-placeholders: ();
@each $placeholder in $placeholders {
  @if $placeholder == "-webkit-input-placeholder" {
    $compiled-placeholder: "&::" + $placeholder;
  }
  @else {
    $compiled-placeholder: "&:" + $placeholder;
  }
  $compiled-placeholders:  append($compiled-placeholders, unquote($compiled-placeholder), comma);
}

$placeholders: $compiled-placeholders;
@debug $placeholders;
```
### Usage Syntax

``` scss
input {
  height: 30px;
  width: 300px;

  #{$placeholders} {
    color: red;
  }
}

```
### CSS Output

``` css
input {
  height: 30px;
  width: 300px; 
}

input::-webkit-input-placeholder, input:-moz-placeholder, input:-ms-input-placeholder {
  color: red; 
}
```
#### Solution:

Perhaps separate rulesets could be generated by using a @mixin with the @content feature in sass?
