### ISSUE TITLE
linear-gradient function

### ISSUE THREAD

**Issue by fmal** [thoughtbot/bourbon#177]
I find the linear-gradient mixin not flexible enough, so sometimes i want to handcode my gradients using plain css.

I have a following code:

``` scss
body.grid {
    background-image: -webkit-linear-gradient(hsla(0,0%,0%,0) 98%, hsla(0,25%,50%,.5) 98%);
    background-image:    -moz-linear-gradient(hsla(0,0%,0%,0) 98%, hsla(0,25%,50%,.5) 98%);
    background-image:      -o-linear-gradient(hsla(0,0%,0%,0) 98%, hsla(0,25%,50%,.5) 98%);
    background-image:         linear-gradient(hsla(0,0%,0%,0) 98%, hsla(0,25%,50%,.5) 98%);
    background-position: 50% 0;
    background-size: #{$base-line-height / $base-font-size}em;
}
```

but the Bourbon's linear-gradient function is breaking the last gradient declaration (standards one).

The output is:

``` css
body.grid {
  background-image: -webkit-linear-gradient(rgba(0, 0, 0, 0) 98%, rgba(159, 96, 96, 0.5) 98%);
  background-image: -moz-linear-gradient(rgba(0, 0, 0, 0) 98%, rgba(159, 96, 96, 0.5) 98%);
  background-image: -o-linear-gradient(rgba(0, 0, 0, 0) 98%, rgba(159, 96, 96, 0.5) 98%);
  background-image: linear, rgba(0, 0, 0, 0) 98%, rgba(159, 96, 96, 0.5) 98%;
  background-position: 50% 0;
  background-size: 1.5em;
}
```

Is it possible to namespace this function or something so it doesn't break normal CSS?

Btw i suggest you remove -ms-linear-gradient from the linear-gradient mixin and please update to the newer syntax (http://www.broken-links.com/2012/01/11/the-new-and-hopefully-final-linear-gradient-syntax/)

Thanks!
