### ISSUE TITLE
use font name with space in font-face mixing

### ISSUE THREAD

**Issue by antonzaytsev** [thoughtbot/bourbon#195]
Hi

bourbon gem is awesome, I love it, thank you for your work you put on it!

My problem was when I included font with below code

``` sass
@include font-face(Klavika Condensed, 'klavika-condensed/klavikaregularcond', $asset-pipeline: true);
```

compiled result was

``` css
@font-face {
  font-family: Klavika Condensed;
  font-weight: normal;
  font-style: normal;
  src: url(/assets/klavika-condensed/klavikaregularcond.eot);
  src: url(/assets/klavika-condensed/klavikaregularcond.eot?#iefix) format("embedded-opentype"), url(/assets/klavika-condensed/klavikaregularcond.woff) format("woff"), url(/assets/klavika-condensed/klavikaregularcond.ttf) format("truetype"), url(/assets/klavika-condensed/klavikaregularcond.svg#Klavika Condensed) format("svg");
}
```

as you can see in part where svg included we have space after "#", because of it font hadn't been included on page. To solve this problem I copied [mixing](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_font-face.scss) in project and changed small part of it.

``` scss
@mixin font-face($font-family, $file-path, $weight: normal, $style: normal, $asset-pipeline: false ) {
  @font-face {
    font-family: $font-family;
    font-weight: $weight;
    font-style: $style;

    @if $asset-pipeline == true {
      src: font-url('#{$file-path}.eot');
      src: font-url('#{$file-path}.eot?#iefix')          format('embedded-opentype'),
      font-url('#{$file-path}.woff')                format('woff'),
      font-url('#{$file-path}.ttf')                 format('truetype'),
      font-url('#{$file-path}.svg#font') format('svg');
    } @else {
      src: url('#{$file-path}.eot');
      src: url('#{$file-path}.eot?#iefix')               format('embedded-opentype'),
      url('#{$file-path}.woff')                     format('woff'),
      url('#{$file-path}.ttf')                      format('truetype'),
      url('#{$file-path}.svg#font')      format('svg');
    }
  }
}
```

so instead of using font name as has-tag I just used simple text

``` scss
# before
font-url('#{$file-path}.svg##{$font-family}') format('svg');
# after
font-url('#{$file-path}.svg#font') format('svg');
```

I'm not sure if it is a best way, if so may be need to change mixing in library?
