### ISSUE TITLE
Feature request: fix buttons in Firefox.

### ISSUE THREAD

**Issue by alexeymuranov** [thoughtbot/bourbon#199]
I have just run into a problem with styling buttons on Firefox, i've found a [solution on SO](http://stackoverflow.com/questions/9186760/) (see the accepted answer).  It turns out that to make buttons behave on Firefox, the following CSS rule has to be added:

``` css
button::-moz-focus-inner,
[type="button"]::-moz-focus-inner {
  padding:0;
  border:0;
}
```

Would it be possible to include this rule into button mixins?

An even better solution might be to provide a tool to clear known browser eccentricities.

Thanks.
