### ISSUE TITLE
Transition mixin improper output

### ISSUE THREAD

**Issue by stevekrueger** [thoughtbot/bourbon#204]
Using the transition() mixin outputs improper CSS with "false" declaration causing the "transition" property not to function properly.

SASS

``` sass
a
  @include transition(all 0.4s ease)
```

CSS

``` css
a {
  -webkit-transition: all 0.4s ease false;
  -moz-transition: all 0.4s ease false false;
  -ms-transition: all 0.4s ease false false;
  -o-transition: all 0.4s ease false false;
  transition: all 0.4s ease false;
}
```

The CSS should output like this:

``` css
a {
  -webkit-transition: all 0.4s ease;
  -moz-transition: all 0.4s ease;
  -ms-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  transition: all 0.4s ease;
}
```
