### ISSUE TITLE
Make $base value of px-to-em function configurable

### ISSUE THREAD

**Issue by hamishtaplin** [thoughtbot/bourbon#254]
Would it be a good idea to be able to set the default value of $base to be configurable via a variable to more easily allow a different base font size? This would eliminate the need to constantly pass in a new base size if you're not working on a 16px font size.

For example:

``` scss
@function em($pxval, $base: $base-font-size) {
  @if not unitless($pxval) {
      $pxval: strip-units($pxval);
  }
  @if not unitless($base) {
      $base: strip-units($base);
  }
  @return ($pxval / $base) * 1em;
}
```
