### ISSUE TITLE
`_is-num()` returning false positive

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/bourbon#360]
The `_is-num()` helper could potentially return false positive:

``` scss
@function _is-num($char) {
  $strings: "0 1 2 3 4 5 6 7 8 9";
  $index: str-index($strings, $char);
  @return if($index, true, false);
}

$is-num: _is-num(" "); // 1
$is-num: _is-num("1 2"); // 3
```

Fixing it:

``` scss
@function _is-num($char) {
  $values: '0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 0 1 2 3 4 5 6 7 8 9;
  $index: index($strings, $char);
  @return $index != false;
}
```

I added actual numbers for safety.
