### ISSUE TITLE
Removing `spec` prefix

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/bourbon#361]
Using the standard version of a property shouldn't be an option, hence the `spec` prefix shouldn't even exist in Bourbon.

Thus, I think the prefixer mixin could be rewritten like this:

``` scss
@mixin prefixer($property, $value, $prefixes: 'webkit') {
  @if $prefixes {
    @each $prefix in $prefixes {
      #{"-" + $prefix + "-" + $property}: $value;
    }
  }

  #{$property}: $value;
}
```

Feel free to change the default value for `$prefixes`. Here is an example:

``` scss
*, *:after, *:before {
  @include prefixer(box-sizing, border-box, moz);
}
```

``` css
*, *:after, *:before {
  -moz-box-sizing: border-box,
  box-sizing: border-box;
}
```

Simple and efficient.
