### ISSUE TITLE
Moving a few things to placeholders

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/bourbon#362]
I think some addons could (should) be moved to placeholders to minimize resulting output. More informations: http://www.sitepoint.com/sass-mixin-placeholder/.

``` scss
%clearfix {
  &:after {
    content: '';
    display: table;
    clear: both;
  }
}
```

If you don't want to break the API (which I can understand), or simply want to keep everything working with mixins, here is what you could do:

``` scss
@mixin clearfix {
  @extend %clearfix;
}
```

Same for `ellipsis` and `hide-text`.
