### ISSUE TITLE
Simpler `size` mixin

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/bourbon#363]
What about this?

``` scss
@mixin size($width: $height: $width) {
  width: $width;
  height: $height;
}
```
