### ISSUE TITLE
Transitions without -ms and -o prefixes on 3.2.1

### ISSUE THREAD

**Issue by caiotarifa** [thoughtbot/bourbon#413]
I'm using the 3.2.1 version of `bourbon` gem with `sass-rails`.

So, I put these variables on top of my file:

``` scss
$prefix-for-webkit:    true;
$prefix-for-mozilla:   true;
$prefix-for-microsoft: true;
$prefix-for-opera:     true;
$prefix-for-spec:      true;
```

But, when I use the `transition` mixin with `transform`:

``` scss
img {
  @include transition-property(transform);
  @include transition-duration(1s); 
}
```

it's compile without `ms` and `o`... Why? And how can I fix it?

``` scss
img {
  -webkit-transition-property: -webkit-transform;
  -moz-transition-property: -moz-transform;
  transition-property: transform;
  -webkit-transition-duration: 1s;
  -moz-transition-duration: 1s;
  transition-duration: 1s;
}
```
