### ISSUE TITLE
Position mixin doesn't work with calc()

### ISSUE THREAD

**Issue by kaishin** [thoughtbot/bourbon#455]
Example:

``` scss
.my-element {
    $var: 20px;
    @include position(absolute, calc(#{$var} - 1px));
}
```

Output:

``` scss
.my-element {
  position: absolute;
}
```
