### ISSUE TITLE
Angle parser doesn't support `turn`

### ISSUE THREAD

**Issue by HugoGiraudel** [thoughtbot/bourbon#519]
```scss
test {
  @include linear-gradient(.5turn, red, blue);
}
```

```css
test {
  background-color: red;
  background-image: -webkit-linear-gradient(-270.5turn, red, blue);
  background-image: linear-gradient(0.5turn,red, blue);
}
```

`-270.5turn` seems a little off here.
