### ISSUE TITLE
Rewriting the linear-gradient prefixer

### ISSUE THREAD

**Issue by HugoGiraudel** [thoughtbot/bourbon#520]
## Disclaimer

Allow me to apology in advance folks, but the current linear-gradient prefixer [is](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/helpers/_linear-angle-parser.scss) [a](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/helpers/_linear-gradient-parser.scss) [complete](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/helpers/_linear-side-corner-parser.scss) [mess](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/helpers/_linear-positions-parser.scss). That being said, any legacy code feels like a mess and as far as I know from @kaishin, this prefixer *is* legacy code from when we had to support a bazillion different syntaxes to emit gradients.

That era is over. As of today, we only have to support 2 syntaxes: the standard one, and the WebKit prefixed one, using old angles/directions.

I really like what you guys are doing with Bourbon, so I decided to give it a go to see how complicated it would be to re-write it. Unfortunately, I don't think you have some kind of specifications defining what should be supported (browsers, Sass versions), when errors should be raised, what warnings are for and so on, so I improvised.

## What do we need?

I came up with a solution that seems pretty decent to me. Before jumping straight on the code, let's have a look at what we need in ordre to cover our needs:

* a function converting angles between allowed units (`deg`, `rad`, `grad`, `turn`);
* a function converting angles/directions to old syntax for WebKit;
* a function checking if a value is an angle/direction;
* a mixin establishing our public API.

## Converting angles

Let's not reinvent the wheel. @chriseppstein has written an amazing function to convert angles, so let's use it right away:

```scss
/// Convert angle
/// @author Chris Eppstein
/// @param {Number} $value - Value to convert
/// @param {String} $unit - Unit to convert to
/// @return {Number} Converted angle
/// @throw "Cannot convert `#{unit($value)}` to `#{$unit}`."
@function convert-angle($value, $unit) {
  $convertable-units: deg grad turn rad;
  $conversion-factors: 1 10grad/9deg 1turn/360deg 3.1415926rad/180deg;
  @if index($convertable-units, unit($value)) and index($convertable-units, $unit) {
    @return $value
             / nth($conversion-factors, index($convertable-units, unit($value)))
             * nth($conversion-factors, index($convertable-units, $unit));
  }
  
  @error "Cannot convert `#{unit($value)}` to `#{$unit}`.";
}
```

## Test if a value is an angle

An angle, in every sense, can be either:

* a number with any of the following unit: `deg`, `rad`, `grad`, `turn`;
* one of the two allowed keywords (e.g. `to right`).

```scss
/// Test if `$value` is an angle
/// @param {*} $value - Value to test
/// @return {Bool}
@function is-angle($value) {
  $is-direction: not not index((to top, to top right, to right top, to right, to bottom right, to right bottom, to bottom, to bottom left, to left bottom, to left, to left top, to top left), $value);
  $is-angle: type-of($value) == 'number' and index('deg' 'grad' 'turn' 'rad', unit($value));
  
  @return $is-direction or $is-angle;
}
```

Verbose but simple in the end.

## Converting to old syntax

Converting an angle (or a direction for that matter) to the old syntax for WebKit is not that hard. First we make sure it's an angle with our brand new `is-angle` function. If it's not, we throw. In case you guys don't support Sass 3.4 yet, feel free to use `@warn <message>; @return null;` instead. 

If it's okay, we either return the legacy equivalent of the keyword if it's a keyword, or compute the old angle if it's an angle. Easy peasy.

```scss
/// Convert an angle/direction to legacy value
/// @param {*} $value - Value to convert
/// @throw "Cannot convert `#{$value}` to legacy syntax because it doesn't seem to be an angle or a direction"
@function legacy-angle($value) {
  @if not is-angle($value) {
    @error "Cannot convert `#{$value}` to legacy syntax because it doesn't seem to be an angle or a direction";
  }

  $conversion-map: ( 
    to top: bottom, 
    to top right: bottom left, 
    to right top: left bottom,
    to right: left,
    to bottom right: top left,
    to right bottom: left top,
    to bottom: top,
    to bottom left: top right,
    to left bottom: right top,
    to left: right,
    to left top: right bottom,
    to top left: bottom right
  );
    
  @if map-has-key($conversion-map, $value) {
    @return map-get($conversion-map, $value);
  }
  
  @return 90deg - convert-angle($value, 'deg');
}
```

## Public API

One thing I noticed in your code is you're trying to do too much. Everything gets parsed, analysed, and so on. If you ask me, it's a bad idea. Use arglists for unknown number of arguments, and leave everything else to Sass rather than trying to control everything.

In my case, I went with the *no-signature* way. Basically, let's accept anything. I deliberately didn't add verifications for number of arguments, throwing if it's lesser than 2, and all this stuff. It's sugar at this point.

Anyway, this is where the magic happens. Once again, we keep it simple. First, we check if `$direction` is an angle; if it's not, we set the direction to `180deg` which is the default value and add the current `$direction` parameter to `$args`. 

From there, we pass everything to the linear-gradient function, and we're done.

```scss
/// Print a linear gradient mixin
/// @param {String | Number} $direction - Direction
/// @param {Arglist} $args - List of arguments
@mixin linear-gradient($direction, $args...) {
  @if not is-angle($direction) {
    $args: ($direction, $args);
    $direction: 180deg;
  }
  
  background: nth(nth($args, 1), 1);
  background: -webkit-linear-gradient(legacy-angle($direction), $args...);
  background: linear-gradient($direction, $args...);
}
```

As you can see, the fallback is the first color from the gradient.

## Tests

To make sure it was working as expected, I ran some tests although keep in mind they are all quite simple at this point. We might want to run some more extensive tests.

```scss
/// Tests variables
/// @type Map
$tests: (
  (to right, red, blue),
  (to top left, red, blue, green),
  (120deg, red 50%, blue 50%),
  (30grad, red, blue),
  (.5turn, red, blue),
  (1rad, red, blue),
  (red, blue)
);

@for $i from 1 through length($tests) {
  test-#{$i} {
    @include linear-gradient(nth($tests, $i)...);
  }
}
```

It outputs:

```css
test-1 {
  background: red;
  background: -webkit-linear-gradient(left, red, blue);
  background: linear-gradient(to right, red, blue);
}

test-2 {
  background: red;
  background: -webkit-linear-gradient(bottom right, red, blue, green);
  background: linear-gradient(to top left, red, blue, green);
}

test-3 {
  background: red;
  background: -webkit-linear-gradient(-30deg, red 50%, blue 50%);
  background: linear-gradient(120deg, red 50%, blue 50%);
}

test-4 {
  background: red;
  background: -webkit-linear-gradient(63deg, red, blue);
  background: linear-gradient(30grad, red, blue);
}

test-5 {
  background: red;
  background: -webkit-linear-gradient(-90deg, red, blue);
  background: linear-gradient(0.5turn, red, blue);
}

test-6 {
  background: red;
  background: -webkit-linear-gradient(32.70422deg, red, blue);
  background: linear-gradient(1rad, red, blue);
}

test-7 {
  background: red;
  background: -webkit-linear-gradient(-90deg, red, blue);
  background: linear-gradient(180deg, red, blue);
}
```

## What's next?

I spent really little time on this, so it might need some tuning to make sure it works across a various range of situations, but overall I think it's both nice and simple.

Before going any further, speaking or PRing, radial gradients and stuff, do you guys share the global idea and like the way code works here?

Any feedback or comment much appreciated. :)

Edit: [code here](http://sassmeister.com/gist/b58f6e2cc3160007c880).
