### ISSUE TITLE
Incorrect alternate values for justify-content in IE

### ISSUE THREAD

**Issue by albaparticle** [thoughtbot/bourbon#526]
Correct value for `space-around` in IE is `distribute`.

Line 235 of `_flex-box`:

``` scss
@elseif $value == "space-around" {
  $alt-value: center;
}
```

should be:

``` scss
@elseif $value == "space-around" {
  $alt-value: distribute;
}
```
