### ISSUE TITLE
Exists redundant prefixes in the keyframe's content

### ISSUE THREAD

**Issue by shivapoudel** [thoughtbot/bourbon#560]
Some related topics #98 #158 but this issue till exists :)

For example, the following code:

``` scss
@include keyframes( axis_pop ) {
    from {
        @include transform( scale(0.8) );
    }
    to {
        @include transform( scale(1) );
    }
}
```

But I got the output

``` css
@-webkit-keyframes axis_pop {
  from {
    -webkit-transform: scale(0.8);
    -moz-transform: scale(0.8);
    -ms-transform: scale(0.8);
    -o-transform: scale(0.8);
    transform: scale(0.8);
  }
  to {
    -webkit-transform: scale(1);
    -moz-transform: scale(1);
    -ms-transform: scale(1);
    -o-transform: scale(1);
    transform: scale(1);
  }
}
@-moz-keyframes axis_pop {
  from {
    -webkit-transform: scale(0.8);
    -moz-transform: scale(0.8);
    -ms-transform: scale(0.8);
    -o-transform: scale(0.8);
    transform: scale(0.8);
  }
  to {
    -webkit-transform: scale(1);
    -moz-transform: scale(1);
    -ms-transform: scale(1);
    -o-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes axis_pop {
  from {
    -webkit-transform: scale(0.8);
    -moz-transform: scale(0.8);
    -ms-transform: scale(0.8);
    -o-transform: scale(0.8);
    transform: scale(0.8);
  }
  to {
    -webkit-transform: scale(1);
    -moz-transform: scale(1);
    -ms-transform: scale(1);
    -o-transform: scale(1);
    transform: scale(1);
  }
}
```

What I seriously need was

``` css
@-webkit-keyframes axis_pop {
  from {
    -webkit-transform: scale(0.8);
  }
  to {
    -webkit-transform: scale(1);
  }
}
@-moz-keyframes axis_pop {
  from {
    -moz-transform: scale(0.8);
  }
  to {
    -moz-transform: scale(1);
  }
}
@keyframes axis_pop {
  from {
    transform: scale(0.8);
  }
  to {
    transform: scale(1);
  }
}
```
