### ISSUE TITLE
How to get important in position

### ISSUE THREAD

**Issue by shivapoudel** [thoughtbot/bourbon#562]
I have done this:

``` scss
.axis-search-tooltip {
    @include position(absolute, 85% !important null null null);
}
```

But I got

``` css
.axis-search-tooltip {
  position: absolute;
  top: 85%; // `!important` is missing guys :)
}
```

What I need strictly was

``` css
.axis-search-tooltip {
  position: absolute;
  top: 85% !important;
}
```
