### ISSUE TITLE
Shorten hide-text mixin

### ISSUE THREAD

**Issue by HugoGiraudel** [thoughtbot/bourbon#583]
Current:

```scss

@mixin hide-text($height: 1em) {
  height: $height;
  line-height: 1.5;
  overflow: hidden;

  &::before {
    content: "";
    display: block;
    width: 0;
    height: 100%;
  }
}
```

This would be enough:

```scss
@mixin hide-text {
  text-indent: 101%;
  overflow: hidden;
  white-space: nowrap;
}
```
