### ISSUE TITLE
Refactor `_is-num` function

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/bourbon#584]
``` scss
@function _is-num($char) {
$values: '0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 0 1 2 3 4 5 6 7 8 9;
$index: index($values, $char);
@return if($index, true, false);
}
```

What about:

``` scss
@function _is-num($char) {
  @return contains('0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 0 1 2 3 4 5 6 7 8 9, $char);
}
```
