### ISSUE TITLE
Refactor contains function

### ISSUE THREAD

**Issue by KittyGiraudel** [thoughtbot/bourbon#587]
``` scss
@function contains($haystack, $needle) {
  @return not not index($haystack, $needle);
}
```

I have hard time believing Libsass still does not support `not` operator... Anyway. We could rewrite the `contains` function to support Libsass.

``` scss
@function contains($haystack, $needle) {
  @if index($haystack, $needle) {
    @return true;
  }

  @return false;
}
```

May I suggest a cute little improvement that does not trigger any API break? 

``` scss
@function contains($haystack, $needles...) {
  @each $needle in $needles {
    @if type-of(index($haystack, $needle)) != "number" {
      @return false;
    }
  }

  @return true;
}
```

This would make it possible to check if a list contains several values at once. For instance:

``` scss
$list: a b c d e;

test {
  a: contains("a" "b" "c", "a");     // true
  b: contains("a" "b" "c", "d");     // false
  c: contains("a" "b" "c", "a" "b"); // true
  d: contains("a" "b" "c", "a" "d"); // false
}
```
