### ISSUE TITLE
Compiling error & after if in "_selection.scss"

### ISSUE THREAD

**Issue by wtrbuit** [thoughtbot/bourbon#591]
I keep getting this error when compiling my CSS with Koala App.

`Syntax error: Invalid CSS after "@if ": expected expression (e.g. 1px, bold), was "& { "`

It seems it doesn’t understand the `&` after the `if` in `_selection.scss`:

``` scss
@if & {
  $before-colons: "&"
}
```
