### ISSUE TITLE
font-face is no longer working with `$asset-pipeline: true`

### ISSUE THREAD

**Issue by chrisnicola** [thoughtbot/bourbon#603]
It is just passing the value in unchanged. Possibly a bug introduced in #595

**Comment by chrisnicola** [comment]
I'm using 4.1.8

**Comment by HugoGiraudel** [comment]
If I may (this is related yet not a fix), the following would be far more elegant while working the same:

```scss
  $formats-map: (
    'eot':   '("#{$file-path}.eot?#iefix")' format("embedded-opentype"),
    'woff2': '("#{$file-path}.woff2")' format("woff2"),
    'woff':  '("#{$file-path}.woff")' format("woff"),
    'ttf':   '("#{$file-path}.ttf")' format("truetype"),
    'svg':   '("#{$file-path}.svg##{$font-family}")' format("svg")
  );

  @each $format, $file-path in $formats-map {
    @if contains($file-formats, $format) {
      $src: append($src, $font-url + $file-path, comma);
    }
  }
```

I removed quote escaping and moved `$font-url` to the append rather than the map itself.
