### ISSUE TITLE
Weird behavior for woff2 fonts with font-face

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/bourbon#633]
I am having an issue with the font-face mixin. When I use `$asset-pipeline: true`, I get the correct paths for all of the font formats (pulling from the path `/assets/fontname-digest.format`) in my fonts folder except for the woff2 font, which has a different path (`/fonts/fontname.woff2`). I have this line in my stylesheet:

```sass
@include font-face(fontello, 'fontello', normal, $asset-pipeline: true);
```

White produces this CSS:
```css
@font-face {
  font-family: fontello;
  font-style: normal;
  font-weight: normal;
  src: url(/assets/fontello-c7d6b3fc8ff75d942cd68d42f95f8192.eot?#iefix) format("embedded-opentype"), url(/fonts/fontello.woff2) format("woff2"), url(/assets/fontello-aef1909e54e9020b4a3fc43e0eb021d7.woff) format("woff"), url(/assets/fontello-6902369cbc821797f104f3a500ed7023.ttf) format("truetype"), url(/assets/fontello-43a1679a6e689edbf5c461f58c19b98e.svg#fontello) format("svg");
}
```

It looks like the prefixer is not assigning the path or digest to the woff2 file.

I am using Bourbon 4.1.1 with Rails 4.2.0.
