### ISSUE TITLE
Issue with @font-face and compressed output with libsass.

### ISSUE THREAD

**Issue by markgoodyear** [thoughtbot/bourbon#688]
Hey!

I'm having some weird issue when using the `@font-face` mixin and `gulp-sass` with it's output set to compressed. When it's set to compressed, I get this output:

```css
/* Output compressed */
@font-face {
  font-family: "GothamBook";
  font-style: normal;
  font-weight: normal;
  src: , url("../fonts/Gotham-Book.eot?#iefix") format("embedded-opentype"), url("../fonts/Gotham-Book.woff") format("woff"), url("../fonts/Gotham-Book.ttf") format("truetype"), url("../fonts/Gotham-Book.svg#GothamBook") format("svg");
}
```

The comma after `src:` prevents it from working.

However, when not compressed, I get this output (prettified for readability):

```css
/* Output normal */
@font-face {
  font-family: "GothamBook";
  font-style: normal;
  font-weight: normal;
  src: url("../fonts/Gotham-Book.eot?#iefix") format("embedded-opentype"), url("../fonts/Gotham-Book.woff") format("woff"), url("../fonts/Gotham-Book.ttf") format("truetype"), url("../fonts/Gotham-Book.svg#GothamBook") format("svg"); 
}
```

The comma is no longer added in and everything works great. This happens using the example directly from the docs too.

I thought this could be a `gulp-sass` issue, however if I use the working output from Bourbon, and set `gulp-sass` to compressed, the comma doesn't appear after compilation — so I'm not sure what is causing the error.

Does anyone have any ideas of what it could be, or to help trace it down?

Cheers :)

__Versions:__
Bourbon 4.2.1
gulp-sass 1.3.3
