### ISSUE TITLE
Add some helpers for styling svgs?

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bourbon#690]
So here's a problem I run in to pretty often… I am styling a parent element that has an svg inside it. My code ends up having to look like this:

```scss
.app-logo {
    svg {
      path,
      text,
      circle {
        fill: $base-font-color;
      }
    }
}
```

Since svgs are in the magic sub-dom-node land they must be referenced directly before their contents can be styled. This seems like great mixin territory. Alternatively this could be a interpolated variable similar to `#{$all-text-inputs}`
