### ISSUE TITLE
Gradient rendering issue

### ISSUE THREAD

**Issue by Doomas** [thoughtbot/bourbon#729]
Hi,

I have following
```
@include linear-gradient(to top, #00ff00, #ff0000);
```
is rendered to
```
background-color: #00ff00;
background-image: -webkit-linear-gradient(bottom, #00ff00, #ff0000);
background-image: linear-gradient(to top,#00ff00, #ff0000, , , , , , , , );
```
The commas at the end is not valid CSS code and therefore the gradient is not displayed in the Browser.

If I Remove the unquote function inside [_linear_gradient.scss] (https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/css3/_linear-gradient.scss) like this 
```
background-image: linear-gradient($pos-spec $full);
```
then it renders correctly to
```
background-color: #00ff00;
background-image: -webkit-linear-gradient(bottom, #00ff00, #ff0000);
background-image: linear-gradient(to top, #00ff00, #ff0000);
```
I'm  not sure if this is a Bourbon problem or a problem with libsass. 

I'm using node-sass 3.0.0 ( libsass 3.2.2 )

**Comment by tysongach** [comment]
Thanks for the heads up, @Doomas.

I can re-create this.

**Comment by greggmoritz** [comment]
I'm also experiencing this on Libsass >3.1.0. Look out for an incoming PR.

**Comment by georgeescott** [comment]
@greggmoritz I too have this issue and have modified the _linear-gradient.scss to match your PR #731 , but it compiles as `linear-gradient(to bottom,#000 #000);` without the comma separating the colour values.

**Comment by georgeescott** [comment]
Working example: @greggmoritz If you update your PR to this it'll work:
```scss
$gradients: $g1, $g2, $g3, $g4, $g5, $g6, $g7, $g8, $g9, $g10;

// Purge null values from list
$full: ();
@each $item in $gradients {
  @if ($item) {
    $full: append($full, $item);
  }
}
$full: zip($full);
```

Then at the bottom change `$full-purged` back to `$full`:
``` scss
background-image: unquote("linear-gradient(#{$pos-spec}#{$full})");
```

**Comment by mistergraphx** [comment]
:+1:

**Comment by greggmoritz** [comment]
@georgeescott Can you provide a little more detail about the engine you're running the compilation on? As well as your simple test case (input, output). I'm unable to reproduce the issue you are seeing. I've run the following sass (taken from [Bourbon docs](http://bourbon.io/docs/#linear-gradient)):

```
@import 'bourbon/bourbon';

.testA {
    @include linear-gradient(#1e5799, #2989d8);
}

.testB {
    @include linear-gradient(to top, #8fdce5, #3dc3d1);
}

.testC {
    @include linear-gradient(to top, #8fdce5, #3dc3d1, $fallback: red);
}

.testD {
    @include linear-gradient(50deg, #1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%);
}
```

I got the exact same (expected) results when I ran that in Ruby Sass v3.4.5 and v 3.4.13, as well as Libsass v3.2.4/Sassc v3.2.1:

```
.testA {
  background-color: #1e5799;
  background-image: -webkit-linear-gradient(#1e5799, #2989d8);
  background-image: linear-gradient(#1e5799, #2989d8);
}

.testB {
  background-color: #8fdce5;
  background-image: -webkit-linear-gradient(bottom, #8fdce5, #3dc3d1);
  background-image: linear-gradient(to top,#8fdce5, #3dc3d1);
}

.testC {
  background-color: red;
  background-image: -webkit-linear-gradient(bottom, #8fdce5, #3dc3d1);
  background-image: linear-gradient(to top,#8fdce5, #3dc3d1);
}

.testD {
  background-color: #1e5799;
  background-image: -webkit-linear-gradient(-320deg, #1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%);
  background-image: linear-gradient(50deg,#1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%);
}
```

**Comment by mistergraphx** [comment]
@greggmoritz : these sassmeister gist, produce the error with libsass 3.2.2 <http://sassmeister.com/gist/6281c9f3cbca51c400e5>

and the result is the same locally for me with libSass / node-sass, latest

  "name": "node-sass",
  "version": "3.1.2",
  "libsass": "3.2.4",

````.scss

$medium-purple: purple;
$dark-purple: darken(purple, 20%);
.selector{
  @include linear-gradient(to top, $medium-purple, $dark-purple);
}

````



````.css
.selector {
  background-color: purple;
  background-image: -webkit-linear-gradient(bottom, purple, #1a001a);
  background-image: linear-gradient(to top,purple, #1a001a, , , , , , , , ); }
````

**Comment by greggmoritz** [comment]
@mistergraphx: Apologies if I wasn't clear what I was asking. Allow me to clarify. @georgeescott eluded that when compiling with the code from PR #731 that I posted, he was still getting unexpected results. I am unable to reproduce the error that he mentioned above and was asking for the specifics of his environment and test case.

The sassmeister that you linked is an example of the original bug, which I _can_ reproduce and the reason this issue was opened.

**Comment by georgeescott** [comment]
@greggmoritz i'm running:
bourbon: 4.2.3
libsass: 3.2.4 (through node-sass 3.1.1 and gulp-sass 2.0.1)
windows: 8.1 Update 1
node: 0.12.0

After running your tests this is what i got:
```css
.testA {
  background-color: #1e5799;
  background-image: linear-gradient(#1e5799, #2989d8, , , , , , , , ); }

.testB {
  background-color: #8fdce5;
  background-image: linear-gradient(to top,#8fdce5, #3dc3d1, , , , , , , , ); }

.testC {
  background-color: red;
  background-image: linear-gradient(to top,#8fdce5, #3dc3d1, , , , , , , , ); }

.testD {
  background-color: #1e5799;
  background-image: linear-gradient(50deg,#1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%, , , , , , ); }
```

testing with RubySass v3.4.13 i got the correct css:
```css
.testA {
  background-color: #1e5799;
  background-image: -webkit-linear-gradient(#1e5799, #2989d8);
  background-image: linear-gradient(#1e5799, #2989d8); }

.testB {
  background-color: #8fdce5;
  background-image: -webkit-linear-gradient(bottom, #8fdce5, #3dc3d1);
  background-image: linear-gradient(to top,#8fdce5, #3dc3d1); }

.testC {
  background-color: red;
  background-image: -webkit-linear-gradient(bottom, #8fdce5, #3dc3d1);
  background-image: linear-gradient(to top,#8fdce5, #3dc3d1); }

.testD {
  background-color: #1e5799;
  background-image: -webkit-linear-gradient(-320deg, #1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%);
  background-image: linear-gradient(50deg,#1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%); }
```

I think this may be an issue with node-sass it seems
