### ISSUE TITLE
Using flexbox not working on Safari

### ISSUE THREAD

**Issue by antonshevchenko** [thoughtbot/bourbon#732]
The `display` mixin for flexbox does not work for Safari. In fact, doing:

```scss
@include display(flex);
```

Results in the following CSS:

```css
display: -webkit- flex; // extra space between -webkit- and flex!
display: flex;
```

The extra space causes Safari to ignore the statement.

**Comment by tysongach** [comment]
What version of Sass or LibSass are you using?

**Comment by antonshevchenko** [comment]
Here's what I got:

```
* sass (3.4.13)
* sass-rails (5.0.3)
```

**Comment by tysongach** [comment]
Hm, I can’t seem to reproduce that output. Here’s what I get (also using Sass 3.4.13):

```css
div {
  display: -webkit-box;
  display: -moz-box;
  display: box;
  display: -webkit-flex;
  display: -moz-flex;
  display: -ms-flexbox;
  display: flex;
}
```

Are you using the latest version of Bourbon, 4.2.3?
