### ISSUE TITLE
Flexbox - firefox

### ISSUE THREAD

**Issue by littlekid** [thoughtbot/bourbon#753]
Shouldn't :
```scss
@mixin display-box {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox; // IE 10
  display: box;
}
```

be updated to (flex instead of box):
```scss
@mixin display-box {
  display: -webkit-box;
  display: -moz-box;
  display: -ms-flexbox; // IE 10
  display: flex;
}
```
