### ISSUE TITLE
Placeholder always returns a color of #999

### ISSUE THREAD

**Issue by anthonator** [thoughtbot/bourbon#796]
We're seeing some weird behavior when using `placeholder`. No matter what we put in the `placeholder` block we always get back a color of `#999`.

Here's our SCSS:

```scss
.navigation-searchbox {
  @include placeholder {
    color: #fff;
  }
}
```

Here's what it compiles to:

```css
.navigation-searchbox::-moz-placeholder {
  color: #999;
  opacity: 1;
}

.navigation-searchbox:-ms-input-placeholder {
  color: #999;
}

.navigation-searchbox::-webkit-input-placeholder {
  color: #999;
}
```

I looked at the mixin code and it looked pretty straightforward. Not sure what I'm doing wrong.
