### ISSUE TITLE
background and background-image has found an error in the mixin.

### ISSUE THREAD

**Issue by gjjoo** [thoughtbot/bourbon#816]
`background` and `background-image` has found an error in the mixin.

```scss
.box {
  @include background(linear-gradient(red, green) left repeat);
  @include background(linear-gradient(red, green) left repeat, radial-gradient(red, orange));
  @include background(url("/images/a.png"), linear-gradient(red, green), center no-repeat orange scroll);
}
```

```css
.box {
  background: linear-gradient(red, green);
  background: linear-gradient(red, green), radial-gradient(red, orange);
  background: url("/images/a.png"), linear-gradient(red, green), center;
}
```

In the output results are not visible attributes such as `left` and `repeat`.

The `_background.scss` and `_background-image.scss` was resolved by modifying the file, as follows:
```scss
// ...
//@each $background in $backgrounds {
@for $i from 1 through length($backgrounds) {
  $background: nth($backgrounds, $i);
// ...
```

After modifying the output results:
```css
.box {
  background: linear-gradient(red, green) left repeat;
  background: linear-gradient(red, green) left repeat, radial-gradient(red, orange);
  background: url("/images/a.png"), linear-gradient(red, green), center no-repeat orange scroll;
}
```

Check, please.
