### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by gibson135** [thoughtbot/bourbon#843]
For some reason this media query is not responding on my iphone. It is an iPhone6. It does respond using Chrome but not on the actually iPhone. 

I'm posting what is as far as I know relevant. 

What is happening is that even though the mobile size has one background color (using this as a test property) it is just using the tablet size anyway. 

```scss
$width:1000;
@import "bourbon/bourbon";
$max-width: em($width);
@import "neat/neat";
@import "bitters/base";

$s:280;
$m:768;
$l:1000;

$small: new-breakpoint($s+px);
$medium: new-breakpoint($m+px);
$large: new-breakpoint($l+px);  

@include media($small) {
  @for $i from 1 through 12 {
    .small-#{$i} {
      @include span-columns($i);    
    }
  }

  body {
    background:blue;
  }
}

@include media($medium) {
  @for $i from 1 through 12 {
    .medium-#{$i} {
      @include span-columns($i);    
    }
  } 

  body{
    background-color:yellow;
  }
}
```
