### ISSUE TITLE
Bourbon - font-face mixin

### ISSUE THREAD

**Issue by magicsass** [thoughtbot/bourbon#857]
Hello, 

Just a quick question about the font-face mixin. 

When I load a font in sass, i used the following code : 

```scss
@font-face {
  font-family: 'Opensans';
  src: url('fonts/opensans/opensans-bold-webfont.eot');
  src: url('fonts/opensans/opensans-bold-webfont.eot?#iefix') format('embedded-opentype'),
       url('fonts/opensans/opensans-bold-webfont.woff2') format('woff2'),
       url('fonts/opensans/opensans-bold-webfont.woff') format('woff'),
       url('fonts/opensans/opensans-bold-webfont.ttf') format('truetype'),
       url('fonts/opensans/opensans-bold-webfont.svg#open_sansbold') format('svg');
  font-weight: 700;
  font-style: normal;
}
```

There is a way to add extra params to the mixin like `font-weight` and `font-style`? 
Sometimes I load the normal font, the bold font, the italic font etc. 

Maybe add this in the mixin :

`font-weight: $font-weight; 
font-style: $font-style;`

Thx for the reply!

**Comment by tysongach** [comment]
Hi @magicsass! You can do this now! The `font-face` mixin already [accepts `$weight` and `$style` arguments](http://bourbon.io/docs/#font-face):

```scss
@include font-face("Opensans", "fonts/opensans/opensans-bold-webfont", bold, normal);
```

That being said, we are actually removing these two arguments in v5.0 (currently [in beta](https://github.com/thoughtbot/bourbon/releases/tag/v5.0.0.beta.1)), in favor of them being passed as content to the mixin, which then get output within the `font-face` block. So the above would turn into this:

```scss
@include font-face("Opensans", "fonts/opensans/opensans-bold-webfont") {
  font-style: normal;
  font-weight: 700;
};
```

Why the change? Well, the mixin wasn’t actually manipulating the weight and style values in any way, so them being arguments in a mixin isn’t strictly required. But we now also gain the ability to pass many things into the mixin for output within the `font-face` block. For example, the new-ish `unicode-range` property:

```scss
@include font-face("calibre", "fonts/calibre") {
  font-style: normal;
  font-weight: 700;
  unicode-range: U+26;
}
```
