### ISSUE TITLE
`before()` and `after()` mixin could be fun

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bourbon#892]
I wouldn't mind a mixin that implants a before of after object. example below:

```scss
.foo {
    @include before() {
        color: blue;
    }

    @include after("→") {
        text-decoration: underline;
    }
}
```

```css
.foo::before {
    content: "";
    color: blue;
}
.foo::after {
    content: "→";
    text-decoration: underline;
}
```

this might be a nice way of condensing code, similar to the `margin` or `size` mixins

**Comment by tysongach** [comment]
@whmii Can you provide some more context as to what the mixin would do and what problem it solves?

**Comment by tysongach** [comment]
@whmii I’m going to close this for now because there aren’t any details or actionable steps to take. You’re always welcome to open a PR, of course!

**Comment by whmii** [comment]
As stated will ad details.

**Comment by tysongach** [comment]
@whmii I’m going to close since this doesn’t have actionable steps to move forward. Please provide information to what problem(s) a `before()` and `after()` mixin would solve, or open a PR.

**Comment by whmii** [comment]
I wouldn't mind a mixin that implants a before of after object. example below:

```scss
.foo {
    @include before() {
        color: blue;
    }

    @include after("→") {
        text-decoration: underline;
    }
}
```

```css
.foo::before {
    content: "";
    color: blue;
}
.foo::after {
    content: "→";
    text-decoration: underline;
}
```

this might be a nice way of condensing code, similar to the `margin` or `size` mixins
