### ISSUE TITLE
Unable to compile a simple animation with transform(rotate) function

### ISSUE THREAD

**Issue by ktamiola** [thoughtbot/bourbon#907]
Hello there! I am working on an animated logo with an SVG element that is supposed to "swing". I have prepared a trivial, test animation in my `SCSS` files:

```scss
@include keyframes(swing) {
    from {
        @include transform(rotateY(0deg));
    }
    to {
        @include transform(rotateY(-360deg));
    }
}
@mixin swingAnimation($delay) {
    @include animation(swing 2.5s linear);
    @include animation-iteration-count(infinite);
    @include animation-delay(#{$delay}s);
}
```
I am attempting to animate an element in `span` with the follwing code.
```scss
.brand-logo-flask {
        background: url('../images/site/flask-empty.svg') no-repeat top left;
        background-size: contain;
        width: 100%;
        .fill {
            background: url('../images/site/fill.svg') no-repeat;
            background-size: 68% 68%;
            background-position: 4px 11px;
            #c170637f-34d6-4fad-9de7-53d02f1bc701 {
                color: color('red', 'base');
            }
        }
        @include swingAnimation(0); // Enable the animation
    }
```
For some reason, (very likely trivial), the animation is not executed. The issue seems to be related to `transform` functions, as I was able to implement trivial `fade in` /  `fade out` in my `SCSS` files, using `opacity` property, and the recipe disclosed above.
