### ISSUE TITLE
invalid property value @include justify-content('center')

### ISSUE THREAD

**Issue by pixelstorm** [thoughtbot/bourbon#939]
### Expected behavior

```css
.row {
    display: -webkit-box;
    display: -moz-box;
    display: -ms-flexbox;
    display: -webkit-flex;
    display: flex;
    align-items: center;
    justify-content: center;
}
```

### Actual behavior

```css
.row {
    -webkit-box-pack: "center";
    -moz-box-pack: "center";
    box-pack: "center";
    -webkit-justify-content: "center";
    -moz-justify-content: "center";
    -ms-justify-content: "center";
    -o-justify-content: "center";
    justify-content: "center";
    -ms-flex-pack: "center";
}
```

### Steps to reproduce behavior

```scss
@include justify-content('center')
```

### Bourbon version

Bourbon 4.2.6

### Environment info

libsass
