### ISSUE TITLE
appearance is not supported with autoprefixer

### ISSUE THREAD

**Issue by kenn** [thoughtbot/bourbon#982]
We shouldn't deprecate `appearance` for prefixing because autoprefixer decided to not support it.

https://github.com/postcss/autoprefixer/issues/43

What do you think?

**Comment by tysongach** [comment]
@kenn Hello!

- [That](https://github.com/postcss/autoprefixer/issues/43) is _very_ old issue from 2013. Autoprefixer [added support for `appearance` in `v6.1`](https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md#61-bil-shaʿb-wa-lil-shaʿb).
- Bourbon 5 still includes our `prefixer` mixin, which was the mixin that did all the hard work under the hood of each individual prefixing mixin that Bourbon used to have. So you can use it to build your own prefixing features, if needed:

  ```scss
  .element {
    @include prefixer(appearance, none, ("webkit", "moz"));
  }

  // CSS Output
  .element {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
  }
  ```

Hope that helps!
