### ISSUE TITLE
Allow parameterizing svg font ID in `font-source-declaration`

### ISSUE THREAD

**Issue by ketan** [thoughtbot/bourbon#983]
### Bourbon version

4.2.7

### Background

I'm using the following snippet:

```scss
@include font-face($font-family: 'Open Sans',
                   $file-path: 'opensans/OpenSans-#{$variant-name}-webfont',
                   $asset-pipeline: true,
                   $file-formats: eot woff ttf svg);
```

The above snippet leads to a couple of problems -

* `bad URI(is not URI?)` exception in `font-source-declaration` (See #686 and #195)
* users are forced to use an SVG ID ($font-family) that's not configurable. I have an SVG that uses a font id that's not the same as `$font-family` . It is currently hardcoded to `"#{$file-path}.svg##{$font-family}"`

I'm happy to submit a PR that allows `font-source-declaration` to accept an (optional) `$svg-id` parameter, that falls back to using `$font-family`
